apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: y8aiwkc6x-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:e92caf91aa5ae8b85d1022549dceb4d7876018b2@sha256:0d0ef2519251079ecdd86eadfdd65bbf3f0819d4805e29468926e5543d129b99
          name: container-image
